from fastapi import APIRouter, HTTPException, Depends
from app.models.chat import ChatRequest, ChatResponse
from app.config import settings
import google.generativeai as genai

router = APIRouter(prefix="/chat", tags=["AI Assistant"])

@router.post("")
@router.post("/")
async def chat_with_assistant(request: ChatRequest):
    try:
        if not settings.GEMINI_API_KEY:
            raise HTTPException(status_code=500, detail="Gemini API key not configured")
            
        genai.configure(api_key=settings.GEMINI_API_KEY)
        model = genai.GenerativeModel('gemini-2.5-flash')
        
        # Build system context from real-time device metrics
        system_prompt = "You are AquaGuard, an expert AI assistant for a smart water quality monitoring system. Guide the user and provide solutions based on their real-time device data. Keep responses concise, helpful, and formatted in markdown."
        
        if request.context:
            ctx = request.context
            context_string = f"\n\nCURRENT WATER SYSTEM CONTEXT:\nHealth Score: {ctx.score}/100 ({ctx.status})\npH Level: {ctx.pH}\nTurbidity: {ctx.turbidity} NTU\nTDS: {ctx.tds} ppm\nTemperature: {ctx.temperature}°C\nFlow Rate: {ctx.flow_rate} L/min"
            system_prompt += context_string
            
        # Combine system prompt with user messages for Gemini prompt struct
        prompt_parts = [system_prompt]
        for msg in request.messages:
            prompt_parts.append(f"{msg.role.capitalize()}: {msg.content}")
        
        full_prompt = "\n".join(prompt_parts) + "\nAssistant:"
            
        # Call Gemini API
        response = model.generate_content(full_prompt)
        
        if not response.text:
             raise ValueError("Empty response generated by Gemini.")
             
        return ChatResponse(response=response.text)
        
    except Exception as e:
        error_msg = str(e)
        if "API_KEY_INVALID" in error_msg or "403" in error_msg:
             return ChatResponse(response="⚠️ I am currently offline because the Gemini API key provided is invalid. Please check your credentials!")
        raise HTTPException(status_code=500, detail=error_msg)
